### PR TITLE
json stats output and various minor fixes

### PR DESCRIPTION
**Pull request by kerolasa**
This pull request contains changes from: https://github.com/conserver/conserver/pull/3

In addition to earlier pull this has ten minor fixes from commit 'update old-style function definitions' to 'fix port output in setproctitle() when IPv6 is supported'. Final two changes add json stats format, and the commit after that couple stats I want to monitor.

### CODE REVIEW

**Comment by conserver** [comment]
What kind of environment are you building with?  I'm attempting a couple different things on my end (centos 7, macos, and solaris) and running into some issues (like the environ extern definition being there on centos 7, but not macos).  But mainly I was curious how you were getting stuff like "-Wnested-externs" warnings (either defaults in your environment or just things you're calling out).  Also, something from the other PR, "make check" isn't actually succeeding (I have a simple fix to apply for it, but thought I'd mention it).

Been busy with my "primary life", but working on making sure nothing here causes any real issues - lots of good stuff!

**Comment by kerolasa** [comment]
I use up to date 'testing packages enabled' archlinux to do my development. Nice thing with this setup is that everything is very close to as new as projects release updates to various things. What comes to warnings - I enable various extras with CFLAGS. The conserver project still reports whole bunch of various minor warnings, but I don't think they are important enough that I'd want to spend a lot of time to make them to go away.

The 'make check' issue you mentioned. I think there are couple options. Merge this, and fix as separate commit to upstream repo. Or send me enough info (or the change) and I'll add it to this pull. Various projects I've contributed tend to prefer first option, choice is yours.

**Comment by kerolasa** [comment]
Just a reminder. It would be nice to get stuff merged.

**Comment by conserver** [comment]
Yeah, sorry about the radio silence. I was testing your changes on various OS/environments and things were rather unhappy. I started rolling back certain things to maintain cross-platform compatibility and it started to get rather involved - then life happened again.

Not sure if you have access or even want to try your version on other Linux and Unix variants, but if you do, you should see the issues. I don’t want to leave all those use cases behind so I’ve been thinking about how to either cherry-pick things or just rollback certain things or just apply mods on top (my local environment has a mix of them all, which has become a bit of a mess). And, unfortunately, some of the major autoconf changes were part of the problem, so the dependencies crop up. 

Anyway, that’s why things have stalled again, and the kinds of things I’m thinking about.

**Comment by kerolasa** [comment]
Are you trying to make all obsolete autotools versions to work, that is, to make this project to work from start point of ./autogen.sh? That is how these problems sound. Did you try 'make dist' with up to date development environment, and use the output tarball from ./configure onward when compiling on old and obsolete systems? The later is how projects usually provide sources so that downstream does not need to worry how up to date autotools are, or are they even installed.

BTW config.log would be useful, or at least error messages. And yes, you guessed right. I don't have old systems or unix variants.

**Comment by conserver** [comment]
I’m certainly not expecting old autotools to work. I was generating everything then just running configure on other systems. There were issues with includes not existing, some not being wrapped with autotools, some other C issues (iirc) and, we’ll, can’t remember exactly. I’ll have to go through this again and have a better organized list to share.

**Pull request closed without merging**
